### ISSUE TITLE
Kibana cannot read logs

### ISSUE THREAD

**Issue by mis101bird** [pblittle/docker-logstash#110]
Hi,
I use this command to run your docker image.
docker run -it -d --name elk -v /home/soselab401/project/servrel/tomcat/logs:/var/log -p 9292:9292 -p 9200:9200 pblittle/docker-logstash
{/home/soselab401/project/servrel/tomcat/logs} is where I put the logs in local machine.
I use the default logstash config and put the local logs to the elk docker.
However, my Kibana didn't show anything...
and I curl {My IP}:9200/*/_search?pretty=true
the hits get nothing...
Why it cannot read the logs?
Thanks for help.

**Comment by pblittle** [comment]
@mis101bird hmm... I'm not sure. I just did a quick test on a cluster and my logs were available in Kibana and ElasticSearch. Are you giving it enough time to load?

**Comment by mis101bird** [comment]
@pblittle Sorry, It is my mistake. I put the log files outside the docker and didn't use volume when I use docker run. It solved now, thank you.

**Comment by pblittle** [comment]
@mis101bird Great. Please let me know if anything else comes up.
