### ISSUE TITLE
Proposal: Optionally install plugins rather than default to installing all

### ISSUE THREAD

**Issue by pblittle** [pblittle/docker-logstash#48]
As it stands today, all plugins are installed when the `Dockerfile` is built. [1] Is this the preferred action to take when building a new image? Or should this be configurable and installed (or not) at runtime? 

Additionally, would it make sense to be able to pass in an array of plugins to install rather than all of this. Moving the plugin installation would help reduce the `Dockerfile` size.

[1] https://github.com/pblittle/docker-logstash/blob/develop/1.4/base/Dockerfile#L11

**Comment by cboettig** [comment]
It seems to me that the [Docker way](https://github.com/docker-library/official-images) of doing this would be to simply provide alternate Dockerfiles (e.g. in subdirectories) that build configurations without all the plugins, and differentiate between these images with tags.  Then a user could run something like `docker run pblittle/docker-logstash:L1.4-E1.1` for logstash and elasticsearch without kibana?

**Comment by pblittle** [comment]
@cboettig, I totally agree. I am going to move to optimizing the images as soon as I ship issues #55 and #49. I am testing my fix for #55 right now.

I still need to create a new issue for the changes we're talking about. I'm planning on creating an `onbuild` directory and image and refactoring the image in `base`. The most common request I get in here is adding/removing `EXPOSE` statements. Next is your request, to be able to change `CMD`. Those should be easy to change.
