### ISSUE TITLE
Proposal: Add support for Logstash 1.5

### ISSUE THREAD

**Issue by pblittle** [pblittle/docker-logstash#50]
Logstash `1.5` is coming soon. We should be prepared and ready to support the new version. To move the project in that direction, I have moved the original `1.4.2` files into a `1.4` directory. [1].

Adding support for `1.5` should only require creating a new `1.5` folder on the project root and dropping the updated build files in.

The next step will be figuring out how to deal with multiple versions in the Docker Hub project. [2]

[1] https://github.com/pblittle/docker-logstash/commit/e47ad5f1e5dc11d75ba89ac3e5eb2e645ce6d54a
[2] https://registry.hub.docker.com/u/pblittle/docker-logstash/

**Comment by pblittle** [comment]
@ianks, @mikehaertl, thanks for questioning my logic. I'm all about upgrading if it makes sense.

@mikehaertl, I'm copying your comment from issue #70 to respond to it.

```
Hmm, I can't really find a version of logstash that has Elasticsearch or Kibana bundled. They all have to be downloaded seperately. All the downloads are now directly available from elasticsearch's download page: http://www.elasticsearch.org/overview/elkdownloads/

The latest versions there are:

Elasticsearch 1.4.4
Logstash 1.4.2
Kibana 4.0.1
So if you download everything from there, that's the latest official ELK stack you get. Why do you think, you need to wait for Logstash 1.5 first?
```

This image is installing logstash `1.4.2` using the tarball from [elasticsearch.org](http://www.elasticsearch.org/overview/logstash/download/). The logstash `1.4.2` source has a bundled version of  Elasticsearch `1.1.1` and Kibana `3.0.1`. I'm not installing the three products individually. That's why I previously noted that any updates this image receives will be embedded in the logstash `1.5.x` source.

Theoretically, I could easily install all three packages from source in this image. I like the idea of keeping this image as simple as possible though. And frankly, the number of install options in this basic setup is enough to make my head spin.

The approach I have taken to upgrade the other components is to just link to a separate `kibana` and/or `elasticsearch` container.

Please let me know if I am missing something. I am by no means a logstash expert.

Thanks again for using the image and chatting about enhancements. I was in a bubble over here for a long time. Input is always welcome and appreciated.

**Comment by epelc** [comment]
@pblittle Perhaps updates would be easier if this was broken up into 3 images. Just a thought it might be to much work/up keep to handle though. BTW great image this is the easiest log stash one to use.

**Comment by pblittle** [comment]
@epelc, sorry I haven't gotten back to you yet. I'll get back to you by the end of the day. Thanks for the kind words.

**Comment by mikehaertl** [comment]
> Please let me know if I am missing something. I am by no means a logstash expert.

Neither am I - and sorry for the delay. This is just a pet project for me. I wanted to try out Kibana and your image seemd the perfect fit. But still couldn't make the latest version work, so I focused on other things meanwhile.

> The logstash 1.4.2 source has a bundled version of Elasticsearch 1.1.1 and Kibana 3.0.1

That's weird. Because there's also this note in the logstash docs  [here](http://logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash):

> Note
>This tutorial specifies running Logstash 1.4.2 with Elasticsearch 1.4.2. Each release of Logstash has a recommended version of Elasticsearch to pair with. Make sure the versions match based on the Logstash version you’re running!

So they even seem to recommend to always have the same versions for logstash and elasticsearch. Why don't the bundle them correctly then? Worth opening an issue over there maybe?

> Perhaps updates would be easier if this was broken up into 3 images.

@epelc I also tend to agree - but this will surely complicate things. The docker convention is, to have 1 process per container. If you split this up, you'd have to maintain 3 repos instead of one and provide a `docker-compose.yml` or something. So maybe this image is the best tradeoff. It's just not something you'd want to use in production.

**Comment by epelc** [comment]
@pblittle No rush

@mikehaertl It would be nice to use this for production as there aren't really any other good logstash images. But having everything in one container also keeps you from worrying so much about mismatched versions.

**Comment by pblittle** [comment]
@mikehaertl, generally speaking, the embedded Elasticsearch shouldn't be used in production. It was embedded for development.

You can definitely use this image in production. I do and a lot of others do also. The convention though is to use this image for Logstash and possibly Kibana. Elasticsearch would be in a separate container.

Take a look at the [test suite](https://github.com/pblittle/docker-logstash/tree/master/1.4/test). You'll find an `elasticsearch-linked` test with a `fig.yml` config file.

```
---
elasticsearch:
  image: dockerfile/elasticsearch
  ports:
    - '9200:9200'
    - '9300:9300'
  command: '/elasticsearch/bin/elasticsearch -Des.http.cors.enabled=true'

logstash:
  build: .
  ports:
   - '9292:9292'
  links:
    - elasticsearch:es
  environment:
    LOGSTASH_TRACE: true
```

That obviously needs to be tweaked to run outside of the test suite, but you'll get the gist.

**Comment by robertd** [comment]
I didn't want to open new issue for this, so I'm going to ask it here.... Are you planning on updating Kibana to 4.0.1 as well?

**Comment by pblittle** [comment]
@robertd, Kibana [has been removed entirely](https://github.com/elastic/logstash/issues/2494) from logstash `1.5`. Based on that, it will no longer be available in this container. I haven't paid much attention to the existing `Kibana 4` containers. I imagine a great container already exists. If it doesn't, I'll gladly write one.

**Comment by robertd** [comment]
@pblittle Thanks for the explanation. I was following this tutorial https://www.cloudgear.net/blog/2015/apache-log-analysis-with-kibana-docker/ and that's how I got here. I really appreciate the effort you're putting in this repo. Thanks!

**Comment by mikehaertl** [comment]
@pblittle I'm still not sure, why it's not possible to simply download the latest versions of all the above into the container. You could then simply tag the different container versions, so the user can decide, which version he wants to use.

I think many people come here to find a simple to use ELK stack and are somewhat disappointet that the latest versions are not available. I'd say it would not be difficult to add them and make everyone happy.
