### ISSUE TITLE
control which services are started by the default CMD?

### ISSUE THREAD

**Issue by cboettig** [pblittle/docker-logstash#57]
The currently documented configurations in  the README all seem to bring `kibana` up along with logstash and elasticsearch service.  It would be excellent to have some way of disabling `kibana` in particular on startup, as it seems to have a much higher memory footprint when the container is running, and may not always be needed.   (though I may be diagnosing this incorrectly, `top` just attributes it to `java`).  

This is potentially related to #48, e.g. clearly this wouldn't be an issue if kibana wasn't installed in the image by default.

**Comment by pblittle** [comment]
@cboettig are you suggesting I simply swap `ENTRYPOINT` out for `CMD` in the `Dockerfile`? That is on my todo list for the next release, `0.12.0`.

**Comment by cboettig** [comment]
Yup, that would do it, thanks

**Comment by pblittle** [comment]
Mind hooking me up with a PR off of the `develop` branch? :smile:
