### ISSUE TITLE
Elasticsearch data is magically persisted when container is deleted/recreated

### ISSUE THREAD

**Issue by mikehaertl** [pblittle/docker-logstash#64]
I am pretty confused about where this container stores it's data. I've created a simple test container, imported some data, then completely removed the container, started a new one - and the old data was still there!

Here's the simple `fig.yml` that I've used:

```
elk:
    image: pblittle/docker-logstash:latest
    volumes:
        - ./logstash/:/opt/logstash/conf.d
        - ./logs/:/data
    ports:
        - "9292:9292"
        - "9200:9200"
    expose:
        - "9292"
        - "9200"
```

and the `logstash/logstash.conf` is

```
input {
    file {
        path => "/data/apache.log"
        start_position => beginning
    }
}
filter {
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
}
output {
    stdout {
        codec => rubydebug
    }
    elasticsearch {
        embedded => true
        host => "127.0.0.1"
        port => "9200"
        protocol => "http"
    }
}
```

I did a `fig up` which created the container. Then I've stopped the container with `Ctrl-C`. I've listed all containers with `docker ps -a` and deleted the correct one with `docker rm -v ab00ac...`.

Then if I do another `fig up`, a new container is created. But the data accumulates! It still has the data from the first container (and even some system logs from the default logstash config file).

So how the heck can I get rid of that data? :)

**Comment by pblittle** [comment]
@mikehaertl is the accumuled data coming from your mounted `apache.log`?

```
input {
    file {
        path => "/data/apache.log"
        start_position => beginning
    }
}
```

If it is, `start_position => beginning` is more than likely the culprit.

**Comment by mikehaertl** [comment]
Well, I've first started a container without a custom configuration. The default configuration seems to index some log files. So i have about 3000 entries like:

```
message":"Unpacking libcryptsetup4:amd64 (2:1.6.6-4) ...","@version":"1","@timestamp":"2015-02-23T19:57:26.250Z","type":"syslog","host":"305207a0f785","path":"/var/log/bootstrap.log"}
```

So i shut down that container, deleted it and tried a fresh new container, this time with my custom config. But the above data is still there - even though it's a completely new container! 

I really don't understand this. If i delete a container, all it's persistent data should be gone with it. How can elasticsearch still have the old data, if it's a totally new container? I've even added the `-v` flag to remove any volumes the container may have used.

I repeated this several times now, and each time i delete the container and create a new one, the old data is still there. Magic?

**Comment by pblittle** [comment]
@mikehaertl do you looking inside of your container and verify the contents of `/opt/logstash/conf.d/logstash/logstash.conf`? I know it's a mounted volume, I just want to make certain we know exactly what the config being used looks like.

**Comment by mikehaertl** [comment]
I've verified. It is my conf file. 

But this really has nothing to do with my local configuration at all. I can leave that away and use your default configuration. 

The problem is really: Why is the elasticsearch data not deleted, if I delete the container. How can it persist and where?

**Comment by pblittle** [comment]
@mikehaertl I'm going to try to reproduce the issue over here. Please let me know if you make any discoveries in the meantime. Crazy... 

FYI, I removed `start_position => "beginning"` from the `syslog` file input in the default config. Definitely a PITA.

**Comment by mikehaertl** [comment]
I've tried with a reboot of my host. No difference: The data is still there and I can't get rid of it.

This is the weirdest thing I've seen with docker so far. Docker must manage volumes in some abstruse way and reuse volumes of deleted containers or something. All this doesn't make sense to me. But maybe I'm just too tired and miss something obvious. So will try again tomorrow.

Thanks for your help - and I really hope you can reproduce it.

**Comment by pblittle** [comment]
@mikehaertl, what environment are you testing in?

**Comment by mikehaertl** [comment]
I'm on Linux Mint 17.1 with latest docker 1.5.0.

**Comment by mikehaertl** [comment]
Ouch:

```
elk:
    image: pblittle/docker-logstash:latest
    volumes:
        - ./logstash/:/opt/logstash/conf.d
        - ./logs/:/data
           ^^^^^^^^^^^
```

Guess what I found in my local `./logs` directory:

```
$ ls -l logs
insgesamt 70692
-rw-r----- 1 mike mike 72145541 Feb 23 20:37 access.log.1
-rw-r--r-- 1 mike mike   207340 Feb 23 21:27 apache.log
drwxr-xr-x 3 root root     4096 Feb 23 20:57 elasticsearch
```

Sorry for the hassle - and thanks for the help. It's really to late over here.

**Comment by pblittle** [comment]
@mikehaertl all good. Glad to help. Let me know if anything else comes up.
