### ISSUE TITLE
Linking volumes for logstash.conf should create a copy of the conf file to edit

### ISSUE THREAD

**Issue by cboettig** [pblittle/docker-logstash#66]
If a user has a logstash.conf file that uses environmental variables like `ES_HOST` and links said file using the pattern recommended in the README:

```
 docker run -d \
  -v <your_logstash_config_dir>:/opt/logstash/conf.d \
...
```

then the container replaces the env vars with their true values.  It seems not ideal for a conf file to be changed from the user's settings when the service is run.  Clearly this doesn't happen if using a remote URL for the conf file, but it often makes more sense to link the file directly (e.g. plays nicely with branches which may have different versions of the conf file).  Seems like it should be straight forward to simply copy the `logstash.conf` file first and edit that?

A related issue: docker let's you link files directly in the same way one would link volumes:

```
 docker run -d \
  -v <your_logstash_config_dir>/logstash.conf:/opt/logstash/conf.d/logstash.conf \
...
```

but for reasons that aren't clear to me, doing this instead of linking a directory causes the container to fail and exit.  Any ideas? (Sorry if that should be a separate issue; but both things are pretty minor).  

Thanks again for this great resource.

**Comment by pblittle** [comment]
@cboettig, do you think #69 created by @mikehaertl is similar to this issue?

**Comment by cboettig** [comment]
Sounds similar to me.

**Comment by mikehaertl** [comment]
Oops, I missed this issue. It's really the same idea, so you can close #69. The only difference is, that I suggest to copy the complete directory. On the other hand: The documentation says, that it will include *all* config files from that directory, which never worked for me anyway. The file had to be named `logstash.conf`.

**Comment by pblittle** [comment]
@mikehaertl 

```On the other hand: The documentation says, that it will include all config files from that directory, which never worked for me anyway. The file had to be named logstash.conf```

You definitely found a bug if all files in `/opt/logstash/conf.d` aren't being loaded.

https://github.com/pblittle/docker-logstash/blob/master/1.4/base/logstash.sh#L74-L112

I'll take a look at it and try to verify.

**Comment by pblittle** [comment]
@mikehaertl I wasn't able to reproduce this issue. I'm going to close it for now. Please reopen if you are still experiencing the problem.
