### ISSUE TITLE
Upgrade to Kibana 4 and Elasticsearch 1.4.4

### ISSUE THREAD

**Issue by mikehaertl** [pblittle/docker-logstash#70]
It would be great to see the latest versions included.

**Comment by pblittle** [comment]
@mikehaertl, this image is using the versions of Kibana and Elasticsearch that are bundled in Logstash `1.4.2`.

I created issue #50 to propose adding Logstash `1.5`. I think the move to `1.5` will be a good time to talk about upgrades.

Until then, your best bet is to link this container to separate Kibana and Elasticsearch containers running the upgrades that you noted.

**Comment by mikehaertl** [comment]
Hmm, I can't really find a version of logstash that has Elasticsearch or Kibana bundled. They all have to be downloaded seperately. All the downloads are now directly available from elasticsearch's download page: http://www.elasticsearch.org/overview/elkdownloads/

The latest versions there are:

 * Elasticsearch 1.4.4
 * Logstash 1.4.2
 * Kibana 4.0.1

So if you download everything from there, that's the latest official ELK stack you get. Why do you think, you need to wait for Logstash 1.5 first?
