### ISSUE TITLE
S appended to https on restarting container

### ISSUE THREAD

**Issue by simonluijk** [pblittle/docker-logstash#72]
When you restart a container that exited for any reason the config is updated. If you have set ES_PROXY_PROTOCOL=https an s is appended to the protocol each time the container is restarted.

I think the replace of the protocol on this line should be updated to include the character after the http. They by failing when the protocol has already been updated.
https://github.com/pblittle/docker-logstash/blob/master/1.4/base/kibana.sh#L34

![https](https://cloud.githubusercontent.com/assets/63589/6802849/dc87a3d4-d233-11e4-9692-aadb51bdb652.jpg)

**Comment by pblittle** [comment]
@simonluijk, thanks man, this is a great find. I'll try to work this in as a hotfix today. I need to write a test to verify, but I think using a something as simple as replacing `http` with `^http[s]?` should do the trick.

If you have time, feel free to submit a PR. :smile:

**Comment by simonluijk** [comment]
That solution was my initial thought too, and maybe the best solution.
But I think it might be best for it to only match the unmodified config.
I don't have a config file to hand. If you send my an example of the
config file I will have a look.

Simon

**Comment by pblittle** [comment]
@simonluijk, I imagine you know, but to be certain, the Kibana config that is being used in this project is embedded in `vendor/kibana` in the Logstash package.

> But I think it might be best for it to only match the unmodified config.

Given the original file is being modified, additional logic will need to be added to track modifications. This is definitely worth exploring. Maybe in a separate issue?

> If you send my an example of the config file I will have a look.

For testing, you should be able to use [the config file](https://github.com/elastic/kibana/blob/v3.0.1/src/config.js) that is vendored in Logstash.

**Comment by simonluijk** [comment]
OK, I have done some testing. This will only match the original config, if it has been modified manually or already updated it won't have any effect. Sorry I am was not able to get a PR together.

`sed -e 's|\"http\:|"https:|g' test.js`

**Comment by pblittle** [comment]
@simonluijk, cool. Thanks for the update. No problem on the PR. I'll try to get something together this afternoon.

**Comment by pblittle** [comment]
@simonluijk do you mind taking a look at #73 and verify the fix before I merge it in?
