### ISSUE TITLE
Can't get tests to work

### ISSUE THREAD

**Issue by griff** [pblittle/docker-logstash#75]
I was working on a fix for #74 and I wanted to run the tests you have in the repository but as far as I can tell they don't work. Is this something you are working on?

**Comment by pblittle** [comment]
@griff sorry I'm just now getting back to you. I've been out of commission for the last few days.

I'm really glad you started by running the test suite, most people don't. :smile: 

All of the tests do pass, but you have to jump through a few hoops to run them. I'll start be showing you how to run them. This example uses the [elasticsearch-embedded](https://github.com/pblittle/docker-logstash/blob/master/1.4/test/Makefile#L15) test:

```shell
$ cd ./1.4/test
$ make test-elasticsearch-embedded
```
That will fire up the container for testing. You then need to `docker exec` to get inside of it.

```shell
$ docker exec -it elasticsearchembedded_logstash_1 /bin/bash
```
Then fire up the [bats](https://github.com/sstephenson/bats) test suite:
```shell
$ ./test.bats
 ✓ Logstash is running
 ✓ Logstash.config contains '{ elasticsearch { embedded => true }'
 ✓ Elasticsearch.yml contains 'script.disable_dynamic: true'
 ✓ Kibana's elasticsearch server is 'http://+window.location.hostname+:9200'
 ✓ Elasticsearch is listening on port '9200'
 ✓ Elasticsearch is listening on port '9300'
 ✓ Kibana is listening on port '9292'
 ✓ Elasticsearch is reachable at '/_status'
 ✓ Kibana dashboard reachable at '/index.html'

9 tests, 0 failures
```
The workflow definitely needs to be tweaked. I more or less pushed up a minimal viable test suite to get as much coverage as possible. A better strategy would be to execute the test suite in the [fig.yml](https://github.com/pblittle/docker-logstash/blob/master/1.4/test/elasticsearch-embedded/fig.yml) file.

Let me know if anything else comes up. Thanks for the help. I really appreciate it.
