### ISSUE TITLE
log4j error?

### ISSUE THREAD

**Issue by saitheexplorer** [pblittle/docker-logstash#76]
I'm seeing this in my docker container logs after the certs have been downloaded.

```
log4j:WARN No appenders could be found for logger (org.elasticsearch.node).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Is this a logstash issue?

**Comment by pblittle** [comment]
@saitheexplorer, from what I understand, it's an Elasticsearch configuration issue. There is a [logstash ticket](https://logstash.jira.com/browse/LOGSTASH-302) from a few years ago describing the problem and provides a [possible workaround](https://gist.github.com/jordansissel/1004979).

I hope this helps. Let me know if you come up with a way to incorporate the workaround.

**Comment by shanesveller** [comment]
We encountered this recently, and in our case it wound up being that the current Docker image was now expecting config files included via Docker volume to be located at `/opt/logstash/conf.d/*` rather than `/opt/logstash.conf`.

**Comment by pblittle** [comment]
@shanesveller, that's really interesting. I'll keep that scenario in mind. Thanks.
