### ISSUE TITLE
turn off elastic search and kibana

### ISSUE THREAD

**Issue by joshuacox** [pblittle/docker-logstash#77]
Is there a way to shut these two down instead of having them start when I have other containers supplying those functions?

**Comment by pblittle** [comment]
@joshuacox, thanks to [a contribution](https://github.com/pblittle/docker-logstash/pull/60) from @aidan-, you are able to selectively run services. 

Unfortunately, I haven't had time to document the feature. Here is the gist from the original PR:

    At the moment it supports 4 modes of operation:

    1. agent - only run the Logstash agent
    2. configtest - run the agent with --configtest
    3. web - only run the Kibana web interface
    4. default, nothing, anything else. - run both the agent and web

So, for example, to only run the Logstash agent, you would simply use the following `docker run` command:

```
docker run --rm -ti --name log -p 9292:9292 pblittle/docker-logstash agent
```

I hope this helps. Let me know if anything else comes up.

**Comment by joshuacox** [comment]
awesome thanks!

**Comment by pblittle** [comment]
@joshuacox glad to help. Let me know if anything else comes up.
