### ISSUE TITLE
Do not force logstash config to be limited to one file named logstash.conf

### ISSUE THREAD

**Issue by jelmstrom** [pblittle/docker-logstash#79]
Logstash has built in capabilities to read multiple config files, if the -f parameter is a directory or contains wildcards. (http://logstash.net/docs/1.4.2/flags) 

Using a hard-coded filename does not only force other containers to use that specific name, but it also prevents the logstash container from reading multiple configuration files.

Starting logstash with a commandline of -f ${LOGSTASH_CONFIG_DIR}  or ${LOGSTASH_CONFIG_DIR}/*.conf, instead of ${LOGSTASH_CONFIG_DIR}/logstash.conf would make a huge  difference.

**Comment by pblittle** [comment]
@jelmstrom, thanks for reporting this issue. Being bound to `logstash.conf` definitely wasn't my intention. All files in `$LOGSTASH_CONFIG_DIR` should be loaded [1].

There must be a bug that needs to be addressed. I'll dig in and try to reproduce the issue.

[1] https://github.com/pblittle/docker-logstash/blob/master/1.4/base/logstash.sh#L143-L148

**Comment by pblittle** [comment]
@jelmstrom I fixed the config file name issue you reported. Thanks again for the bug report. This fix will go out in the next release. Please let me know if it doesn't resolve your issue.
