### ISSUE TITLE
After container run: Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9

### ISSUE THREAD

**Issue by Boran** [pblittle/docker-logstash#88]
Hi, I pulled this container to have a look at logstash, which I do not yet know.

After building the container (with the options noted in the Readme for "Full Elk stack": -p 9292:9292 9200:9200) . 
Then connecting to port 9200 there is nothing and on 9292, one see a minimal UI with a message above saying "Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9"

Perhaps a few tips on where to go from here?

**Comment by pblittle** [comment]
@Boran, sure. Glad to help. Do you mind trying to build the container again? I found a bug this AM which may or may not be related to your issue.

**Comment by Boran** [comment]
I still see the same error.

The last bit of the docker logs says:
2015-05-04 20:35:29 (17.6 MB/s) - ‘/opt/ssl/logstash-forwarder.crt’ saved [1345/1345]
Sending logstash logs to /var/log/logstash/logstash.log.
log4j:WARN No appenders could be found for logger (org.elasticsearch.node).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by pblittle** [comment]
@Boran, the last bit of your log output looks fine. What does `docker ps -a` return?

**Comment by Boran** [comment]
oot@logstash:~# ps -ax
  PID TTY      STAT   TIME COMMAND
 1 ?        Ssl    4:02 /usr/bin/java -Xmx500m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb agent --config /opt/logstash/conf.d --log /var/log/logstash/logstash.log -- web
16314 ?        Ss     0:00 su - root
16319 ?        S      0:00 -su
16341 ?        R+     0:00 ps -ax

/var/log/logstash/logstash.log is empty

ls /opt/logstash
LICENSE  README.md  bin  conf.d  conf.d2  lib  locales  patterns  spec  vendor

ls /opt/logstash/conf.d
data  logstash.conf

**Comment by pblittle** [comment]
@Boran I'm really not sure where to go with the debugging without more information. I ran the full stack command on a few machines successfully. Let me know if you have any additional information to give me to help debug/reproduce, otherwise I'll close the issue.

**Comment by pblittle** [comment]
@Boran, sorry I couldn't help. Let me know if you gain any additional insight.

**Comment by davehun** [comment]
I am seeing the same thing
Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above.

also get Exception in thread ">output" org.elasticsearch.discovery.MasterNotDiscoveredException: waited for [30s]
	at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$3.onTimeout(org/elasticsearch/action/support/master/TransportMasterNodeOperationAction.java:180)
	at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(org/elasticsearch/cluster/service/InternalClusterService.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(java/lang/Thread.java:745)
 in the console

**Comment by pblittle** [comment]
@davehun do you mind giving me a little more information? It would help me to see the output of `docker -v`, your docker run command, and the config file you're using.

There has to be a use case that I'm not aware of or testing. Hopefully we can get to the bottom of it.

**Comment by therealgambo** [comment]
I was having this same issue, turned out to be a miss configuration of kibana trying to connect via http, but elasticsearch was being provided over https.

**Comment by pblittle** [comment]
@therealgambo thanks for the update. Do you see a bug in my documentation?
