### ISSUE TITLE
Error Could not load dashboards/default.json. Please make sure it exists

### ISSUE THREAD

**Issue by crccheck** [pblittle/docker-logstash#92]
If you access Kibana via a name other than the 172.x.x.x  ip or localhost, you get the error: `Error Could not load dashboards/default.json. Please make sure it exists` because the web server serves a 403 response for nearly everything.

In my case, I set up dns entries so I can talk to my containers by name instead of ip, and going to http://elk.docker:9292/index.html#/dashboard/file/default.json returns that error.

**Comment by pblittle** [comment]
@crccheck I ran a few tests locally and I'm not able to reproduce this issue. 

I am able to access Kibana using my container IP `192.168.59.103`:

```bash
$ curl -i http://192.168.59.103:9292/index.html#/dashboard/file/default.json
HTTP/1.1 200 OK
content-type: text/html;charset=utf-8
content-length: 2073
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
```

I am also able to access Kibana after adding `elk.docker` to `/etc/hosts`:

```shell
$ curl -i http://elk.docker:9292/index.html#/dashboard/file/default.json
HTTP/1.1 200 OK
content-type: text/html;charset=utf-8
content-length: 2073
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
```

This might be a `CORS` issue. Is `http.cors.allow-origin` set in your `elasticsearch.yml` file?

**Comment by crccheck** [comment]
I wasn't using a custom `elasticsearch.yml`. http://elk.docker:9292/index.html#/dashboard/file/default.json actually does load for me, but if you open the network window it's full of HTTP 403 errors. 

`"NetworkError: 403 Forbidden - http://elk.docker:9292/app/dashboards/default.json?1432526707006"`

But if I use `curl`, it does load.

This may be a kibana thing.

**Comment by pblittle** [comment]
@crccheck, this very well could be a Kibana issue. I'm going to close this issue for now. Please repoen if you find it is specific to this project.
