### ISSUE TITLE
could you update please to logstash 1.5.0?

### ISSUE THREAD

**Issue by Alino** [pblittle/docker-logstash#98]
because I am facing this issue https://github.com/elastic/logstash/issues/1756
it should be solved in 1.5.0
Thank you

**Comment by Alino** [comment]
sorry it wasn't fixed in 1.5.0 but newer version would be still nice to have :D

**Comment by pblittle** [comment]
@Alino I plan to knock this out as soon as possible. It is related to issue #50.
